export const shaanRenaissance = {};

shaanRenaissance.SRdomains = {
    Shaan: "Shaan",
    Technique: "Technique",
    Savoir: "Savoir",
    Social: "Social",
    Arts: "Arts",
    Magie: "Magie",
    Rituels: "Rituels",
    Survie: "Survie",
    Combat: "Combat",
    Nécrose: "Nécrose",
    }
shaanRenaissance.pouvoirs = {
    trihns: {
        esprit: "Esprit",
        ame: "Âme",
        corps: "Corps",
        necrose: "Nécrose"
    },
    pouvoirSelect: {
        none: "",
        AstucedeTechnique: "Astuce de Technique",
        SecretdeSavoir: "Secret de Savoir",
        PrivilegedeSocial: "Privilège de Social",
        CréationdArts: "Création d'Arts",
        SymbiosedeShaan: "Symbiose de Shaan",
        SortdeMagie: "Sort de Magie",
        TransedeRituel: "Transe de Rituels",
        ExploitdeSurvie: "Exploit de Survie",
        TactiquedeCombat: "Tactique de Combat",
        TourmentdeNécrose: "Tourment de Nécrose"
    },
    pouvoirRank: {
        none: "",
        Rank1: "Rang 1",
        Rank2: "Rang 2",
        Rank3: "Rang 3",
        Rank4: "Rang 4",
    },
    pouvoirType: {
        none: "",
        attaque: "Attaque",
        défense: "Défense",
        déplacement: "Déplacement",
        amélioration: "Amélioration",
        altération: "Altération",
        invocation: "Invocation",
        controle: "Contrôle",
        perception: "Perception",
        recuperation: "Récupération"
    },
    pouvoirFréquence: {
        none: "",
        permanente: "Permanente",
        tour: "1/Tour",
        situation: "1/Situation",
        jour: "1/Jour",
        transition: "1/Transition"
    },
    pouvoirActivation: {
        none: "",
        geste: "1 Geste",
        action: "1 Action",
        actions: "2 Actions",
        actioncible: "1 Action par Cible",
        heure: "1 Heure",
        jour: "1 Jour",
        transition: "1 Transition",
        testparaction: "1 Test par Action",
        testparheure: "1 Test par Heure",
        testparjour: "1 Test par Jour",
        deuxactoumoinscorps: "2 Actions ou 1 Actions et -1 de Corps",
        untestdeuxactoumoinscorps: "1 Test toutes les 2 Actions ou 1 Test et -1 points de corps par Action"
    },
    pouvoirPortée: {
        none: "",
        soi: "Soi",
        contact: "Contact",
        interaction: "Interaction",
        distance: "Distance",
        horizon: "Horizon",
    }
};
shaanRenaissance.acquis = {
    category:{
        Armement: "Armement",
        Armimales: "Armimales",
        Artefacts: "Artefacts",
        Manuscrits: "Manuscrits",
        Outils: "Outils",
        Protections: "Protections",
        Relations: "Relations",
        Richesses: "Richesses",
        Technologie: "Technologie",
        Transport: "Transport"
    },
    class:{
        class1: "Classe 1",
        class2: "Classe 2",
        class3: "Classe 3",
        class4: "Classe 4",
        class5: "Classe 5"
    },
    caste:{
        none: "",
        Novateur: "Novateur",
        Erudit: "Erudit",
        Négociant: "Négociant",
        Artiste: "Artiste",
        Shaaniste: "Shaaniste",
        Magicien: "Magicien",
        Elementaliste: "Elementaliste",
        Voyageur: "Voyageur",
        Combattant: "Combattant",
        Ombre: "Ombre"
    },
    voie:{
        none: "",
        terrestre: "Terrestre",
        aerienne: "Aérienne",
        maritime: "Maritime"
    },
    Ressources: {
        Verre: "Verre",
        Bois: "Bois",
        Or: "Or",
        Population: "Population",
        Pierre: "Pierre",
        Trihnite: "Trihnite",
        Animal: "Animal",
        Cultures: "Cultures",
        Métal: "Métal",
        Hydrocarbure: "Hydrocarbure"
    }
}
shaanRenaissance.activeEffectChanges = {
    "data.prestige":"SR.prestige",
    "data.skills.Technique.specialisations.engrenages.value":"engrenages",
    "data.skills.Technique.specialisations.pilotage":"pilotage",
    "data.skills.Technique.specialisations.recuperation":"recuperation",
    "data.skills.Technique.specialisations.sensdelapierre":"sensdelapierre",
    "data.skills.Technique.specialisations.sensdubois":"sensdubois",
    "data.skills.Technique.specialisations.sensducuir":"sensducuir",
    "data.skills.Technique.specialisations.sensdumetal":"sensdumetal",
    "data.skills.Technique.specialisations.sensdutissu":"sensdutissu",
    "data.skills.Technique.specialisations.sensduverre":"sensduverre",
    "data.skills.Technique.specialisations.technologie":"technologie",
    "data.skills.Savoir.specialisations.alchimie":"alchimie",
    "data.skills.Savoir.specialisations.bibliotheque":"bibliotheque",
    "data.skills.Savoir.specialisations.botanique":"botanique",
    "data.skills.Savoir.specialisations.culturehumaine":"culturehumaine",
    "data.skills.Savoir.specialisations.esoterisme":"esoterisme",
    "data.skills.Savoir.specialisations.geologie":"geologie",
    "data.skills.Savoir.specialisations.histoiredheos":"histoiredheos",
    "data.skills.Savoir.specialisations.medecine":"medecine",
    "data.skills.Savoir.specialisations.protocoles":"protocoles",
    "data.skills.Savoir.specialisations.zoologie":"zoologie",
    "data.skills.Social.specialisations.arpege":"arpege",
    "data.skills.Social.specialisations.bluff":"bluff",
    "data.skills.Social.specialisations.commerce":"commerce",
    "data.skills.Social.specialisations.diplomatie":"diplomatie",
    "data.skills.Social.specialisations.enseignement":"enseignement",
    "data.skills.Social.specialisations.langageprimal":"langageprimal",
    "data.skills.Social.specialisations.languesexotiques":"languesexotiques",
    "data.skills.Social.specialisations.psychologie":"psychologie",
    "data.skills.Social.specialisations.seduction":"seduction",
    "data.skills.Social.specialisations.vieurbaine":"vieurbaine",
    "data.skills.Arts.specialisations.artsappliques":"artsappliques",
    "data.skills.Arts.specialisations.artsdufeu":"artsdufeu",
    "data.skills.Arts.specialisations.chant":"chant",
    "data.skills.Arts.specialisations.comedie":"comedie",
    "data.skills.Arts.specialisations.deguisement":"deguisement",
    "data.skills.Arts.specialisations.gastronomie":"gastronomie",
    "data.skills.Arts.specialisations.langageducorps":"langageducorps",
    "data.skills.Arts.specialisations.lettres":"lettres",
    "data.skills.Arts.specialisations.musique":"musique",
    "data.skills.Arts.specialisations.trucages":"trucages",
    "data.skills.Shaan.specialisations.embiose":"embiose",
    "data.skills.Shaan.specialisations.empathieanimale":"empathieanimale",
    "data.skills.Shaan.specialisations.empathieantheenne":"empathieantheenne",
    "data.skills.Shaan.specialisations.empathieminerale":"empathieminerale",
    "data.skills.Shaan.specialisations.empathievegetale":"empathievegetale",
    "data.skills.Shaan.specialisations.intuition":"intuition",
    "data.skills.Shaan.specialisations.reve":"reve",
    "data.skills.Shaan.specialisations.soinsdelame":"soinsdelame",
    "data.skills.Shaan.specialisations.soinsdelesprit":"soinsdelesprit",
    "data.skills.Shaan.specialisations.soinsducorps":"soinsduCorps",
    "data.skills.Magie.specialisations.arcanes":"arcanes",
    "data.skills.Magie.specialisations.conjuration":"conjuration",
    "data.skills.Magie.specialisations.defensemagique":"defensemagique",
    "data.skills.Magie.specialisations.enchantement":"enchantement",
    "data.skills.Magie.specialisations.invocation":"invocation",
    "data.skills.Magie.specialisations.incandescence":"incandescence",
    "data.skills.Magie.specialisations.maitrisedesschemes":"maîtrisedesschemes",
    "data.skills.Magie.specialisations.regenerationdetrihn":"regenerationdeTrihn",
    "data.skills.Magie.specialisations.transfert":"transfert",
    "data.skills.Magie.specialisations.voile":"voile",
    "data.skills.Rituels.specialisations.ritedarts":"ritedarts",
    "data.skills.Rituels.specialisations.ritedecombat":"ritedeCombat",
    "data.skills.Rituels.specialisations.ritedelanimal":"ritedelanimal",
    "data.skills.Rituels.specialisations.ritedemagie":"ritedemagie",
    "data.skills.Rituels.specialisations.ritedenecrose":"ritedenecrose",
    "data.skills.Rituels.specialisations.ritedesavoir":"ritedeSavoir",
    "data.skills.Rituels.specialisations.ritedeshaan":"ritedeShaan",
    "data.skills.Rituels.specialisations.ritedesocial":"ritedeSocial",
    "data.skills.Rituels.specialisations.ritedesurvie":"ritedeSurvie",
    "data.skills.Rituels.specialisations.ritedetechnique":"ritedeTechnique",
    "data.skills.Survie.specialisations.acrobatie":"acrobatie",
    "data.skills.Survie.specialisations.caravane":"caravane",
    "data.skills.Survie.specialisations.cultureheossienne":"cultureHeossienne",
    "data.skills.Survie.specialisations.culturenecrosienne":"culturenecrosienne",
    "data.skills.Survie.specialisations.discretion":"discretion",
    "data.skills.Survie.specialisations.educationphysique":"educationphysique",
    "data.skills.Survie.specialisations.monture":"monture",
    "data.skills.Survie.specialisations.navigation":"navigation",
    "data.skills.Survie.specialisations.viesauvage":"vieSauvage",
    "data.skills.Survie.specialisations.vigilance":"vigilance",
    "data.skills.Combat.specialisations.armeslancees":"armeslancees",
    "data.skills.Combat.specialisations.armesdemelee":"armesdemelee",
    "data.skills.Combat.specialisations.armesaprojectiles":"armesaprojectiles",
    "data.skills.Combat.specialisations.armimales":"armimales",
    "data.skills.Combat.specialisations.enginsdeguerre":"enginsdeguerre",
    "data.skills.Combat.specialisations.esquive":"esquive",
    "data.skills.Combat.specialisations.forcer":"forcer",
    "data.skills.Combat.specialisations.intimidation":"intimidation",
    "data.skills.Combat.specialisations.pugilat":"pugilat",
    "data.skills.Combat.specialisations.strategie":"strategie",
    "data.skills.Nécrose.specialisations.armeshumaines":"armeshumaines",
    "data.skills.Nécrose.specialisations.biomorphie":"biomorphie",
    "data.skills.Nécrose.specialisations.cauchemar":"cauchemar",
    "data.skills.Nécrose.specialisations.contrebande":"contrebande",
    "data.skills.Nécrose.specialisations.corruption":"corruption",
    "data.skills.Nécrose.specialisations.explosifs":"explosifs",
    "data.skills.Nécrose.specialisations.fraude":"fraude",
    "data.skills.Nécrose.specialisations.harcelement":"harcelement",
    "data.skills.Nécrose.specialisations.larcin":"larcin",
    "data.skills.Nécrose.specialisations.pactenecrotique":"pactenecrotique"
}
